### ISSUE TITLE
There is no 'easy to get' palette

### ISSUE THREAD

**Issue by alzedd** [flrnd/candid.vim#3]
Sorry for the unclear title.

Can you share a palette, like [nord theme does in the readme](https://github.com/arcticicestudio/nord) in order to make themes for Iterm2, kitty and such.

**Comment by flrnd** [comment]
Hey, nothing to be sorry!
Updated README.md with a temporary solution.

**Comment by nickrivadeneira** [comment]
Also interested in this. The colorscheme looks great, but can't make use of it until I can get kitty or Ubuntu Terminal colors compatible.

To give you an idea of what it looks like even after setting Ubuntu Terminal colors to the ones in the README:

![Screenshot from 2019-12-16 10-56-18](https://user-images.githubusercontent.com/1431996/70921650-b9531d00-1ff2-11ea-84e6-6ec589ca9831.png)

**Comment by flrnd** [comment]
Hey, @nickrivadeneira glad you like the color scheme.  You need to be sure that your vim is properly configured to use true color. Your screenshot is the result of  only 256 color scheme.

**Comment by nickrivadeneira** [comment]
@flrnd Thanks! I have tried to fix this problem so many times but never came to a solution. My terminal and tmux are both set up to run true color, but I could never get Vim configured to do so. Turns out I needed to set `set termguicolors` in `~/.config/nvim/init.vim` ([Source](https://github.com/neovim/neovim/wiki/FAQ#how-can-i-use-true-color-in-the-terminal)).

**Comment by flrnd** [comment]
@nickrivadeneira cool! Glad we found the problem!
